ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "positionType" TEXT NOT NULL DEFAULT 'service';
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "positionType" TEXT NOT NULL DEFAULT 'service';
ALTER TABLE "OfferItem" ADD COLUMN IF NOT EXISTS "positionType" TEXT NOT NULL DEFAULT 'service';
ALTER TABLE "InvoiceItem" ADD COLUMN IF NOT EXISTS "positionType" TEXT NOT NULL DEFAULT 'service';
